=== DominikFalkiewicz/projectXML/projekt.xsd
<?xml version="1.0" encoding="utf-8"?>
<xsd:schema elementFormDefault="qualified" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <xsd:element name="drzewo" type="drzewo"/>
    
    <xsd:complexType name="drzewo">
        <xsd:sequence>
            <xsd:group ref="grupy"/>
        </xsd:sequence>
    </xsd:complexType>

    <!-- GRUPY -->
    <xsd:group name="grupy">
        <xsd:choice>
            <xsd:sequence>
                <xsd:group ref="organizmy" minOccurs="1" maxOccurs="1"/>
                <xsd:group ref="dodatki" minOccurs="1" maxOccurs="1"/>
            </xsd:sequence>
            <xsd:sequence>
                <xsd:group ref="dodatki" minOccurs="1" maxOccurs="1"/>
                <xsd:group ref="organizmy" minOccurs="1" maxOccurs="1"/>
            </xsd:sequence>
        </xsd:choice>
    </xsd:group>
    
    <xsd:group name="organizmy">
        <xsd:sequence>
            <xsd:element name="klady" type="klady" minOccurs="1" maxOccurs="1"/>
            <xsd:element name="gatunki" type="gatunki" minOccurs="1" maxOccurs="1"/>
        </xsd:sequence>
    </xsd:group>

    <xsd:group name="dodatki">
        <xsd:sequence>
            <xsd:element name="nisze" type="nisze" minOccurs="1" maxOccurs="1"/>
            <xsd:element name="rangi" type="rangi" minOccurs="1" maxOccurs="1"/>
            <xsd:element name="okresy" type="okresy" minOccurs="1" maxOccurs="1"/>
        </xsd:sequence>
    </xsd:group>
    
    <!-- PODGRUPY -->
    <xsd:complexType name="klady">
        <xsd:sequence>
            <xsd:element name="klad" type="klad" minOccurs="1" maxOccurs="unbounded"/>
        </xsd:sequence>
    </xsd:complexType>
    
    <xsd:complexType name="gatunki">
        <xsd:sequence>
            <xsd:element name="gatunek" type="gatunek" minOccurs="0" maxOccurs="unbounded"/>
        </xsd:sequence>
    </xsd:complexType>
    
    <xsd:complexType name="nisze">
        <xsd:sequence>
            <xsd:element name="nisza" type="nisza" minOccurs="0" maxOccurs="unbounded"/>
        </xsd:sequence>
    </xsd:complexType>
    
    <xsd:complexType name="rangi">
        <xsd:sequence>
            <xsd:element name="ranga" type="ranga" minOccurs="0" maxOccurs="unbounded"/>
        </xsd:sequence>
    </xsd:complexType>
    
    <xsd:complexType name="okresy">
        <xsd:sequence>
            <xsd:element name="okres" type="okres" minOccurs="1" maxOccurs="unbounded"/>
        </xsd:sequence>
    </xsd:complexType>
    
    <!-- KLAD -->
    <xsd:complexType name="klad">
        <xsd:sequence>
            <xsd:element name="knazwa" type="knazwa" minOccurs="1" maxOccurs="1"/>
        </xsd:sequence>
        <xsd:attribute name="id" type="kid" use="required"/>
        <xsd:attribute name="ojciec" type="kid" use="optional"/>
        <xsd:attribute name="ranga" type="rid" use="optional"/>
        <xsd:attribute name="okresy" type="oid_list" use="required"/>
    </xsd:complexType>

    <xsd:simpleType name="oid_list">
        <xsd:list itemType="oid"/>
    </xsd:simpleType>

    <xsd:simpleType name="kid">
        <xsd:restriction base="xsd:string">
            <xsd:pattern value="k[1-9][0-9]*"/>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="knazwa">
        <xsd:restriction base="xsd:string">
            <xsd:pattern value="[A-Z][a-z]+"/>
            <xsd:maxLength value="50"/>
        </xsd:restriction>
    </xsd:simpleType>
    
    <!-- GATUNEK -->
    <xsd:complexType name="gatunek">
        <xsd:sequence>
            <xsd:element name="gnazwa" type="gnazwa" minOccurs="1" maxOccurs="1"/>
        </xsd:sequence>
        <xsd:attribute name="rodzaj" type="kid" use="required"/>
        <xsd:attribute name="nisza" type="nid" use="optional"/>
    </xsd:complexType>

    <xsd:simpleType name="gnazwa">
        <xsd:restriction base="xsd:string">
            <xsd:pattern value="[a-z]+"/>
            <xsd:maxLength value="50"/>
        </xsd:restriction>
    </xsd:simpleType>
    
    <!-- NISZA -->
    <xsd:complexType name="nisza">
        <xsd:sequence>
            <xsd:element name="nnazwa" type="xsd:string" minOccurs="1" maxOccurs="1"/>
            <xsd:element name="nopis" type="xsd:string" minOccurs="0" maxOccurs="1"/>
        </xsd:sequence>
        <xsd:attribute name="id" type="nid" use="required"/>
    </xsd:complexType>

    <xsd:simpleType name="nid">
        <xsd:restriction base="xsd:string">
            <xsd:pattern value="n[1-9][0-9]*"/>
        </xsd:restriction>
    </xsd:simpleType>
    
    <!-- RANGA -->
    <xsd:complexType name="ranga">
        <xsd:sequence>
            <xsd:element name="rnazwa" type="rnazwa" minOccurs="1" maxOccurs="1"/>
        </xsd:sequence>
        <xsd:attribute name="id" type="rid" use="required"/>
    </xsd:complexType>

    <xsd:simpleType name="rid">
        <xsd:restriction base="xsd:string">
            <xsd:pattern value="r[1-9][0-9]*"/>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="rnazwa">
        <xsd:restriction base="xsd:string">
            <xsd:pattern value="[A-Z][a-z]+"/>
            <xsd:maxLength value="50"/>
        </xsd:restriction>
    </xsd:simpleType>
    
    <!-- OKRES -->
    <xsd:complexType name="okres">
        <xsd:sequence>
            <xsd:element name="onazwa" type="xsd:string" minOccurs="1" maxOccurs="1"/>
        </xsd:sequence>
        <xsd:attribute name="id" type="oid" use="required"/>
        <xsd:attribute name="skrot" type="xsd:string" use="required"/>
    </xsd:complexType>
    
    <xsd:simpleType name="oid">
        <xsd:restriction base="xsd:string">
            <xsd:pattern value="o[1-9][0-9]*"/>
        </xsd:restriction>
    </xsd:simpleType>
    
</xsd:schema>

=== DominikFalkiewicz/projectXML/projekt_out.xml
<?xml version="1.0" encoding="UTF-8"?><?xml-stylesheet type="text/css" href="projekt.css"?><!DOCTYPE drzewo SYSTEM "projekt.dtd">
<drzewo bcg="./obrazki/drzewo.jpg" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="projekt.xsd">
    <dnazwa>Caseazaury</dnazwa>
    <ostatnia_modyfikacja>2019-12-30T09:14:53</ostatnia_modyfikacja>
    <klady id="k">
        <klad id="k1" okresy="o1 o2" wymarly="1">
            <knazwa>Caseasauria</knazwa>
        </klad>
        <klad id="k2" ojciec="k1" okresy="o2" ranga="r2" wymarly="1">
            <knazwa>Eothyrididae</knazwa>
        </klad>
        <klad id="k3" ojciec="k1" okresy="o1 o2" ranga="r2" wymarly="1">
            <knazwa>Caseidae</knazwa>
        </klad>
        <klad id="k4" ojciec="k3" okresy="o2" ranga="r1" wymarly="1">
            <knazwa>Cotylorhynchus</knazwa>
        </klad>
        <klad id="k5" ojciec="k2" okresy="o2" ranga="r1" wymarly="1">
            <knazwa>Eothyris</knazwa>
        </klad>
        <klad id="k6" ojciec="k2" okresy="o2" ranga="r1" wymarly="1">
            <knazwa>Oedaleops</knazwa>
        </klad>
    </klady>
    <gatunki id="g">
        <gatunek imf="./obrazki/EothyrisF.jpg" img="./obrazki/Eothyris.jpg" nisza="n1" rodzaj="k5" wymarly="1">
            <gnazwa>parkeyi</gnazwa>
            <data_odkrycia>1937-06-21</data_odkrycia>
            <najwcz_datowanie>290100000</najwcz_datowanie>
        </gatunek>
        <gatunek imf="./obrazki/OedaleopsF.jpg" img="./obrazki/Oedaleops.jpg" nisza="n3" rodzaj="k6" wymarly="1">
            <gnazwa>campi</gnazwa>
        </gatunek>
        <gatunek imf="./obrazki/CotylorhynchusF.jpg" img="./obrazki/romeri.jpg" nisza="n2" rodzaj="k4" wymarly="1">
            <gnazwa>romeri</gnazwa>
            <data_odkrycia>1937-02-01</data_odkrycia>
        </gatunek>
        <gatunek imf="./obrazki/CotylorhynchusF.jpg" img="./obrazki/bransoni.jpg" nisza="n2" rodzaj="k4" wymarly="1">
            <gnazwa>bransoni</gnazwa>
            <data_odkrycia>1962-12-29</data_odkrycia>
        </gatunek>
        <gatunek imf="./obrazki/CotylorhynchusF.jpg" img="./obrazki/Cotylorhynchus.jpg" nisza="n2" rodzaj="k4" wymarly="1">
            <gnazwa>hancocki</gnazwa>
            <data_odkrycia>1953-04-12</data_odkrycia>
        </gatunek>
    <gatunek img="abhdsfhb" nisza="n1" rodzaj="k5" wymarly="1"><gnazwa>romeri</gnazwa></gatunek></gatunki>
    <nisze id="n">
        <nisza id="n1" img="./obrazki/drapieżnik.png">
            <nnazwa>Drapieżnik</nnazwa>
            <nopis>Zwierzęta odżywiające się innymi zwierzętami.</nopis>
        </nisza>
        <nisza id="n2" img="./obrazki/roślinożerca.png">
            <nnazwa>Roślinożerca</nnazwa>
            <nopis>Zwierzęta odżywiające się roślinami.</nopis>
        </nisza>
        <nisza id="n3" img="./obrazki/owadożerca.png">
            <nnazwa>Owadożerca</nnazwa>
            <nopis>Zwieżęta odżywiające się owadami.</nopis>
        </nisza>
    </nisze>
    <rangi id="r">
        <ranga id="r1">
            <rnazwa>Rodzaj</rnazwa>
        </ranga>
        <ranga id="r2">
            <rnazwa>Rodzina</rnazwa>
        </ranga>
    </rangi>
    <okresy id="o">
        <okres id="o1" skrot="C">
            <onazwa>Karbon</onazwa>
            <poczatek sufiks="miliona lat temu">358.9</poczatek>
            <koniec sufiks="miliona lat temu">298.9</koniec>
        </okres>
        <okres id="o2" skrot="P">
            <onazwa>Perm</onazwa>
            <poczatek sufiks="miliona lat temu">298.9</poczatek>
            <koniec sufiks="miliona lat temu">252.17</koniec>
        </okres>
    </okresy>
</drzewo>
